# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "ShanChain.xcworkspace", scheme: "ShanChain")
    upload_to_app_store
  end

  lane :beta do
      build_app(export_method: "ad-hoc")
      pgyer(api_key: "4f26608844e57b9b96245793e11ce649", user_key: "9a87d0e786998ecdb55071337eb8df6f", update_description: "update by fastlane")
  end
end
