# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
      # 增加build版本号
    increment_build_number
    scheme_name = "ShanChain"
    output_name = "#{scheme_name}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"
    gym(
      export_method: "app-store", 
      export_xcargs: "-allowProvisioningUpdates",
      clean:true, #打包前clean项目
      scheme: scheme_name,# target的名字
      output_directory:".././api_output_directory/AppStore",#ipa的存放目录
  )
    #build_app(workspace: "ShanChain.xcworkspace", scheme: "ShanChain")
    #upload_to_app_store
    deliver
  end

  lane :beta do
    scheme_name = "ShanChain"
    output_name = "#{scheme_name}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"
  	gym(
      clean:true, #打包前clean项目
      output_directory:".././api_output_directory/pgyer",#ipa的存放目录
      export_method: "ad-hoc", 
       #output_name:get_build_number()#输出ipa的文件名为当前的build号
  )

      build_app(export_method: "ad-hoc")
      pgyer(api_key: "524793b674ba75a634b1cb2468ed1605", user_key: "4b3765e514060845a86d793b0291868d", update_description: "update by fastlane")
  end
end
