/**
 * @providesModule CommonUrlMap
 *
 * Created by flyye on 2017/10/17.
 */

const CommonUrlMap = {
  SPACE_ROLE_MODEL_LIST: '/v1/character/model/query/spaceId',
  SPACE_ROLE_MODEL: '/v1/character/model/query/modelId',
  CHANGE_SPACE_ROLE_MODEL: '/v1/character/model/modify',
  CHANGE_USER_CHARACTER: '/v1/character/modify',
  DELETE_USER_CHARACTER: '/v1/character/delete',
  DELETE_SPACE_ROLE_MODEL: '/v1/character/model/delete',
  CANCEL_FOCUS_SOMEONE: '/v1/focus/unfocus',
  CANCEL_SUPPORT_CHARACTER: '/v1/character/model/unSupport',
  CHEATE_USER_CHARACTER: '/v1/character/create',
  GET_MY_FOCUS_LIST: '/v1/focus/myFocus',
  GET_MY_FUNS_LIST: '/v1/focus/funs',
  FIND_MODEL_BY_NAME: '/v1/character/model/query/name',
  FIND_CHARACTER_LIST_BY_USER: '/v1/character/query/userId',
  FIND_CHARACTER_BY_CHARID: '/v1/character/query',
  CHREATE_USER_MODEL: '/v1/character/model/create',
  ADD_CHATACTER_FOCUS: '/v1/focus/focus',
  ADD_CHATACTER_SUPPORT: '/v1/character/model/support',
  FIND_MODEL_LIST_ORDER: '/v1/character/model/list/spaceId',
  FIND_MODEL_BY_TAG: '/v1/character/query/tag/id',
  MODIFY_SPACE_ANNO: '/v1/spaceAnno/modify',
  DELETE_SPACE_ANNO: '/v1/spaceAnno/delete',
  DELETE_SPACE_NEWS: '/v1/spaceNews/delete',
  DELETE_SPACE_NOTICE: '/v1/spaceNotice/delete',
  FIND_ANNO_LIST_BY_TITLE: '/v1/spaceAnno/list',
  FIND_NEWS_LIST_BY_TITLE: '/v1/spaceNews/list',
  GET_NEWS_BY_ID: '/v1/spaceNews/query',
  FIND_NOTICE_LIST_BY_SPACE: '/v1/spaceNotice/list',
  CHREATE_SPACE_ANNO: '/v1/spaceAnno/create',
  CHREATE_SPACE_NEWS: '/v1/spaceNews/create',
  CHREATE_SPACE_NOTICE: '/v1/spaceNotice/create',
  MODIFY_SPACE: '/v1/space/modify',
  MODIFY_SPACE_BG_TEXT: '/v1/space/bgtext/modify',
  DELETE_SPACE_IMGS: '/v1/space/pic/del',
  CREATE_SPACE: '/v1/space/create',
  DELETE_SPACE: '/v1/space/delete',
  DELETE_SPACE_BG_TEXT: '/v1/space/bgtext/del',
  CANCEL_FOCUS_SPACE: '/v1/space/unFavorite',
  FOCUS_SPACE: '/v1/space/favorite',
  GET_SPACE_IMGS: '/v1/space/pic/list',
  GET_SPACE_LIST_BY_IDS: '/v1/space/list/spaceId',
  FIND_SPACE_LIST_BY_NAME: '/v1/space/list/name',
  ADD_SPACE_IMG: '/v1/space/pic/add',
  ADD_SPACE_BG_TEXT: '/v1/space/bgtext/create',
  ADD_SPACE_MANAGER: '/v1/spaceManager/create',
  SWITCH_SPACE: '/v1/space/switch',
  DELETE_SPACE_MANAGER: '/v1/spaceManager/delete',
  ADD_TAG_FOR_SPACE: '/v1/space/tag/add',
  DELETE_SPACE_TAG: '/v1/space/tag/remove',
  GET_MY_FOCUS_SPACE_LIST: '/v1/space/list/favorite',
  GET_SPACE_MANAGER_LIST: '/v1/spaceManager/list',
  GET_SPACE_BGTEXT_LIST: '/v1/space/bgtext/list',
  FIND_SPACE_LIST_BY_TAG: '/v1/space/list/tag',
  REPORT_STOTY: '/v1/story/report',
  UPDATE_STORY: '/v1/story/update',
  DELETE_STORY: '/v1/story/delete',
  DELETE_STORY_COMMENT: '/v1/story_comment/delete',
  ADD_STORY: '/v1/story/add',
  BLOCK_STORY: '/v1/story/block',
  RECOVERY_STORY: '/v1/story/recovery',
  ADD_STORY_COMMENT: '/v1/story_comment/add',
  REMOVE_STORY_SUPPORT: '/v1/story/support/remove',
  ADD_STORY_SUPPORT: '/v1/story/support/add',
  REMOVE_COMMENT_SUPPORT: '/v1/story_comment/support/remove',
  ADD_COMMENT_SUPPORT: '/v1/story_comment/support/add',
  GET_STORY_LINE_BY_ID: '/v1/story/chain/id',
  FIND_CHARACTER_LIST_BY_MODEL: '/v1/character/query/modelId',
  FIND_TOPIC_LIST_BY_SPACEID: '/v1/topic/query/spaceId',
  FIND_BACKGROUND_BY_USER: '/v1/userinfo/background',
  USER_FEEDBACK: '/v1/feedback/user',
  GET_MY_SPACE_LIST: '/v1/space/list/mine',
  GET_SPACE_NOVEL_LIST: '/v1/story/query/spaceId/hot',
  GET_MY_STORY_LIST: '/v1/story/query/mine',
  GET_CHARACTER_BRIEF_INFO_LIST: '/v1/character/query/brief',
  GET_DRAFT_LIST_BY_SPACEID: '/v1/draft/get',
  IS_SPACE_IS_FAV: '/v1/space/isFav',
  CHARACTER_FOCUS_CHECK: '/v1/focus/isFav/list',
  CHANGE_USER_INFO: '/v1/userinfo/update',
  USERINFO_GET_BY_ID: '/v1/userinfo/get',
  GET_MODEL_FAV_STATUS: '/v1/character/model/isFav',
  MODEL_ISFAV_LIST: '/model/isFav/list',
  DELETE_SPACE_RULE_LIST: '/v1/spaceNotice/delete/list',
  GET_ACCOUNT_BINDING_INFO: '/v1/user/bound',
  BIND_OTHER_ACCOUNT: '/v1/user/bind_other_account',
  GET_STORY_BY_LIST: '/v1/story/get',
  GET_MY_COMMENTS_LIST: '/v1/storyComment/list/mine',
  GET_STORY_SUPPORT_LIST:'/v1/story/support/list',
  STORY_ISFAV_LIST: '/v1/story/isFav/list',
  STORY_SUPPORT_ADD: '/v1/story/support/add',
  STORY_SUPPORT_REMOVE: '/v1/story/support/remove',
};

module.exports = CommonUrlMap;
